config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hello, only: %i/index show/
  resources :anime, only: %i/index/
end

app/models/anime.rb
class Anime < ApplicationRecord
   belongs_to :cour, foreign_key: :cours_id

   searchable do
      text :title
      text :title_short1
      text :title_short2
      text :title_short3
      text :twitter_account
      text :twitter_hash_tag
      text :public_url
      integer :cours_id
      time :created_at
   end

   def open_graph
      return nil unless public_url.present?
      return @og if @og
      @og = Rails.cache.fetch(public_url, expires_in: 3.months) do
         puts "accessing #{public_url}"
         OpenGraph.new public_url
      end
   end

   def image_urls
      og = open_graph
      return nil unless og
      og.images
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cour.rb
class Cour < ApplicationRecord
end

app/models/hello.rb
class Hello < ApplicationRecord
  def party_all_night!
    puts "#{id} will party all night!"
  end
end

app/controllers/anime_controller.rb
class AnimeController < ApplicationController
   def index
      if params[:q].present?
         search = Anime.search do
            fulltext params[:q]
            if params[:year].present? && params[:cours].present?
               cour = Cour.find_by year: params[:year], cours: params[:cours]
               with(:cours_id, cour.id) if cour
            end
         end
         @animes = search.results
         return
      end
      @animes = Anime.joins(:cour).includes(:cour).all
      %i/year cours/.each do |key|
         if params[key].present?
            @animes = @animes.where("cours.#{key} = ?", params[key])
         end
      end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
    @hellos = Hello.all
  end
  def show
    @hello = Hello.find params[:id]
  end
end

app/helpers/anime_helper.rb
module AnimeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/anime/index.html.haml
= form_tag anime_index_path, method: :get do
  = text_field_tag :q, params[:q]
  - if params[:year].present?
    = hidden_field_tag :year, params[:year]
  - if params[:cours].present?
    = hidden_field_tag :cours, params[:cours]
  = submit_tag '検索'

%table.anime_list
  %tr
    %th
      ID
    %th
      クール
    %th
      タイトル
    %th
      公式Twitter
    %th
      画像
  - @animes.each.with_index(1) do |anime, idx|
    %tr
      %td
        = idx
      %td
        = "#{anime.cour.year}/#{anime.cour.cours}Q"
      %td
        - unless anime.sequel.zero?
          = "第#{anime.sequel}期"
          %br
        = link_to anime.title, anime.public_url
      %td
        = link_to "@#{anime.twitter_account}", "https://twitter.com/#{anime.twitter_account}"
        %br
        = link_to "##{anime.twitter_hash_tag}", "https://twitter.com/hashtag/#{anime.twitter_hash_tag}"
      %td
        - if anime.image_urls.present?
          - anime.image_urls.first(5).each_with_index do |image_url, i|
            - if i.zero?
              .image_box_large
                = image_tag image_url, class: 'anime_image'
            - else
              .image_box_small
                = image_tag image_url, class: 'anime_image'
                

app/views/hello/index.html.haml
%h1
  hello haml

%table
  %tr
    %th
      id
    %th
      greet
  - @hellos.each do |hello|
    %tr
      %td
        = link_to hello.id, hello_path(id: hello.id)
      %td
        = hello.greet

app/views/hello/show.html.haml
#hello
  .hello_id
    = @hello.id
  .hello_greet
    = @hello.greet

= link_to :index, hello_index_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHello</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>